DataField For/With Actiongroups
SAP/odata-vocabularies pull request #158
Opened 2021-12-20 13:24 UTC by BerSie

This enables semantic grouping of actions/navigations. The UI / consumer could bundle these actions together.

2021-12-20 13:42 UTC, ralfhandl requested changes
Looks good: please check the explicitly annotated restriction list to data field subtypes

2021-12-20 13:43 UTC, ralfhandl submitted a review, later dismissed

2021-12-20 14:26 UTC, RaizoC submitted a review, later dismissed

2021-12-23 12:30 UTC, BerSie commented
sorry for bothering you again ... I forgot the "experimental" tag.

2021-12-23 13:20 UTC, RaizoC approved these changes

2021-12-23 13:30 UTC, merged