DataField.Value does not allowed mixed-type collections
SAP/odata-vocabularies pull request #187
Opened 2022-06-09 15:57 UTC by HeikoTheissen

2022-06-09 16:03 UTC, ralfhandl requested changes

2022-06-09 16:03 UTC, ralfhandl commented on vocabularies/UI.json
> +                    "Collection(Edm.Decimal)",
```suggestion
                    "Collection(Edm.Decimal)",
                    "Collection(Edm.Double)",
```

If we allow `Edm.Single`, we should also allow `Edm.Double`, given that two of our backends support `Edm.Double` and do not support `Edm.Single`.

2022-06-09 16:59 UTC, ralfhandl approved these changes

2022-06-10 06:19 UTC, BerSie approved these changes
OK - these types are a good starting point.

2022-06-10 07:35 UTC, ralfhandl approved these changes

2022-06-10 10:54 UTC, uhlmannm approved these changes

2022-06-22 06:16 UTC, ThomasChadzelek approved these changes

2022-06-22 06:17 UTC, merged