Common.DraftXxx: sync with RAP implementation
SAP/odata-vocabularies pull request #192
Opened 2022-07-20 14:25 UTC by ralfhandl

1.	DiscardAction ist nicht mehr experimental
2.	AdditionalNewActions ist nicht mehr experimental
3.	EditAction kann einen optionalen Parameter „PreserveChanges“ (Edm.Boolean) haben (schon lange)
•	The action can provide an optional parameter “PreserveChanges” of type “Edm.Boolean” that may be used to ensure outdated drafts of another user are not overwritten (see below).
4.	NewAction and AdditionalNewActions können einen optionalen Parameter “ResultIsActiveEntity” (Edm.Boolean) haben (schon lange)
•	The action can provide an optional parameter "ResultIsActiveEntity" of type Edm.Boolean to indicate whether via the action a draft or an active instance should be created. Default is “false”, i.e. the creation of a draft instance.
5.	DraftNode: PreparationAction is deprecated
•	I even wonder if the complete annotation “DraftNode” is deprecated as it is always empty (in the meantime). That a node is activated via and belongs to the draft root is indicated via a separate annotation “DraftActivationVia”. [@Marcel Waechter](mailto:marcel.waechter@sap.com) can you confirm the annotation “DraftNode” is NOT used any more in FE V4 (and V2)?
6.	ShareAction hat einen neuen Parameter “ShareAll” (Edm.Boolean)

2022-07-25 14:07 UTC, RaizoC approved these changes

2024-11-29 10:35 UTC, HeikoTheissen requested changes
Purely typographical review

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            - `PreserveChanges`: optional, of type `Boolean`, `true` means that an outdated draft of another user is not overwritten</String>
```suggestion
- `PreserveChanges`: optional, of type `Boolean`, `true` means that an outdated draft of another user is not overwritten</String>
```
You want a bulleted list in Markdown, right?

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            New drafts may also be created by POSTing an entity with property IsActiveEntity=false (default) to the entity set.</String>
```suggestion
- `ResultIsActiveEntity` of type `Boolean` with default `false`, `true` means that an active entity is created

New drafts may also be created by POSTing an entity with property IsActiveEntity=false (default) to the entity set.</String>
```

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            - `ResultIsActiveEntity` of type `Boolean` with default `false`, `true` means that an active entity is created</String>
```suggestion
- `ResultIsActiveEntity` of type `Boolean` with default `false`, `true` means that an active entity is created</String>
```

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
```suggestion
- `Users`: collection of structure with properties
```

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            &#xA0;&#xA0;&#x25E6; `UserID` of type `String`
```suggestion
  - `UserID` of type `String`
```

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            &#xA0;&#xA0;&#x25E6; `UserAccessRole` of type `String` with possible values `O` (owner, can perform all draft actions), and `E` (editor, can change the draft)
```suggestion
  - `UserAccessRole` of type `String` with possible values `O` (owner, can perform all draft actions), and `E` (editor, can change the draft)
```

2024-11-29 10:35 UTC, HeikoTheissen commented on vocabularies/Common.xml
> +            the `Users` parameter is optional in this case, provide it to actively notify the listed users</String>
```suggestion
- `ShareAll` of type `Boolean` with default value `false`, `true` means sharing with all users that are authorized to create drafts; the `Users` parameter is optional in this case, provide it to actively notify the listed users</String>
```

2024-11-29 10:54 UTC, RaizoC commented
If we do not deprecate the complete "DraftNode" (which is only used as tag and thus redundant to "DraftActivationVia", we should at least remove or deprecate the ValidationFunction inside that was never used.

2024-11-29 11:52 UTC, ralfhandl commented
> we should at least remove or deprecate the ValidationFunction

That is already deprecated:
https://github.com/SAP/odata-vocabularies/blob/c941c4ef39997efcdcd92f93e41e61e26a203f80/vocabularies/Common.xml#L1136-L1146

2024-12-03 12:35 UTC, ralfhandl commented
> @RaizoC Should we deprecate the whole `DraftNode` now?

Deprecated the term

2024-12-03 12:47 UTC, RaizoC commented
> > @RaizoC Should we deprecate the whole `DraftNode` now?
> 
> Deprecated the term

I would deprecate it as it only adds redundancy, but we @MarcelWaechter should confirm.

2025-03-31 12:19 UTC, HeikoTheissen approved these changes

2025-03-31 12:47 UTC, HeikoTheissen approved these changes

2025-03-31 12:47 UTC, merged