Counterparts for two new @ObjectModel annotations
SAP/odata-vocabularies pull request #202
Opened 2022-10-28 13:19 UTC by ralfhandl

- `@ObjectModel.objectIdentifier.oidElement` --> `ODM.identifier`
- `@ObjectModel.odmEntity.name` --> `ODM.entityName`

2022-10-28 13:25 UTC, HeikoTheissen requested changes

2022-10-28 13:25 UTC, HeikoTheissen commented on vocabularies/ODM.xml
> +        <Annotation Term="Core.Description" String="This annotation points to an ODM entity as a general concept, not a concrete version thereof" />
```suggestion
        <Annotation Term="Core.Description" String="Name of an ODM entity as a general concept, not a concrete version thereof" />
```

2022-10-28 14:51 UTC, HeikoTheissen approved these changes

2022-11-02 09:36 UTC, ralfhandl commented
@swennemers can we merge this PR?

2022-11-02 12:48 UTC, swennemers commented
@ralfhandl wow, you are so fast. So far the usage of the @ODM vocabulary is not aligned with the stakeholders. Not sure if that is enough to already merge the PR.

2022-11-02 13:37 UTC, ralfhandl commented
@swennemers Then let's wait for the stakeholder alignment.

Minor note: in CAP this is the `@ODM` vocabulary - case matters, annotations starting with a lowercase letter (for example `@cds`) are treated as "internal annotations" and are not propagated to OData $metadata or OpenAPI, only annotations starting with an uppercase letter (`@Core`, `@Capabilities`, ...) are propagated to OData $metadata.

2022-12-07 14:44 UTC, swennemers requested changes
Thanks a lot for the update to the PR. @everyone reading this PR in the future, these annotations have now their direct representation in CDS: @ODM.entityName and @ODM.oid.

2022-12-07 14:44 UTC, swennemers commented on vocabularies/ODM.json
> +            "@Core.LongDescription": "The technical type can be UUID or String (any length), and the value must be stable and unique at least within type and landscape (better globally). \nAn entity
```suggestion
            "@Core.LongDescription": "The field is an alternative key to the entity. The technical type can be UUID or String (typically length 128), and the value must be stable and unique at least within type and landscape (better globally). \nAn entity may have other IDs, i.e. a local ID and other alternative IDs. "
```

2022-12-07 14:44 UTC, swennemers commented on vocabularies/ODM.json
> +            "@Core.LongDescription": "This implies that the annotation cannot provide any contract about properties being contained in a model.\nThe annotated entity type thus is _not_ an implementat
@ralfhandl I am not sure about this description. With recent ODM additions, there are multiple representations of a single entity...

2022-12-07 15:23 UTC, swennemers commented on vocabularies/ODM.json
> +            "@Core.LongDescription": "This implies that the annotation cannot provide any contract about properties being contained in a model.\nThe annotated entity type thus is _not_ an implementat
not sure where you found this specific description and long description... But I missed that the xml is the source of truth of the json and md files

2022-12-07 15:30 UTC, swennemers requested changes

2022-12-07 15:30 UTC, swennemers commented on vocabularies/ODM.xml
> +          <String>The technical type can be UUID or String (any length), and the value must be stable and unique at least within type and landscape (better globally).
```suggestion
          <String>The technical type can be UUID or String (typical length 128), and the value must be stable and unique at least within type and landscape (better globally). 
```

2022-12-07 15:30 UTC, swennemers commented on vocabularies/ODM.xml
> +          <String>The technical type can be UUID or String (any length), and the value must be stable and unique at least within type and landscape (better globally).
I understand that wasn't part of the CDS request, but there was a link to an SAP internal ADR which isn't available outside.

2022-12-07 15:30 UTC, swennemers commented on vocabularies/ODM.xml
> +An entity may have other IDs, i.e. a local ID and other alternative IDs. This is the ID used for ODM.</String>
```suggestion
An entity may have other IDs, i.e. a local ID and other alternative IDs. </String>
```
"This is the ID used for ODM" should be obvious from being an ODM ID. It doesn't add more to it, does it? Therefore I would remove it.

2022-12-07 15:30 UTC, swennemers commented on vocabularies/ODM.xml
> +The annotated entity type thus is _not_ an implementation of the ODM entity, it only represents this ODM entity.</String>
```suggestion
          <String>The annotated OData entity is one of many representations of the ODM entity. Annotating the OData entity with the annotation helps consumers finding APIs that process or expose the same entity.</String>
```
A new proposal trying to express it a bit more positively.

2022-12-08 07:31 UTC, swennemers approved these changes

2022-12-08 07:38 UTC, merged

2022-12-08 07:42 UTC, HeikoTheissen requested changes

2022-12-08 07:42 UTC, HeikoTheissen commented on vocabularies/ODM.xml
> +          <String>The annotated OData entity is one of many representations of the ODM entity. Annotating the OData entity with the annotation helps consumers finding APIs that process or expose the
```suggestion
          <String>The annotated OData entity is one of many representations of the ODM entity. Annotating the OData entity with this term helps consumers find APIs that process or expose the same entity.</String>
```

2022-12-08 07:49 UTC, ralfhandl commented on vocabularies/ODM.xml
> +          <String>The annotated OData entity is one of many representations of the ODM entity. Annotating the OData entity with the annotation helps consumers finding APIs that process or expose the
Will open a new PR for this change