PersonalData: rename EndOfPurposeDate to PotentialEndOfBusinessDate
SAP/odata-vocabularies pull request #257
Opened 2023-06-06 12:28 UTC by ralfhandl

2023-06-06 12:41 UTC, HeikoTheissen requested changes

2023-06-06 13:55 UTC, HeikoTheissen requested changes

2023-06-06 13:55 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +              <PropertyValue Property="Value" String="PotentialEndOfBusinessDate" />
```suggestion
              <PropertyValue Property="Value" String="EndOfBusinessDate" />
```
With the changed description, I see no need for the prefix "Potential" any more. Suggest to drop it, it is confusing.

2023-06-06 14:24 UTC, HeikoTheissen submitted a review, later dismissed

2023-06-06 15:40 UTC, ralfhandl commented on vocabularies/PersonalData.xml
> -                ([GDPR article 5 (1b)](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&amp;from=EN#d1e1807-1-1)),
No, GDPR was the original scope of the vocabulary.

EndOfBusinessDate seems to be the only term not defined by GDPR, and creating a new vocabulary just for it seems overkill.

2023-06-06 15:45 UTC, HeikoTheissen approved these changes

2023-07-26 06:21 UTC, HeikoTheissen approved these changes

2023-07-26 13:20 UTC, merged