Instance annotations for recursive hierarchies
SAP/odata-vocabularies pull request #258
Opened 2023-06-13 06:00 UTC by HeikoTheissen

2023-06-20 12:32 UTC, HeikoTheissen commented
To be merged after Albatross 2023-06-27

2023-06-20 15:44 UTC, ThomasChadzelek approved these changes

2023-06-26 10:48 UTC, uhlmannm approved these changes

2023-06-27 13:18 UTC, agoerler requested changes
@HeikoTheissen - found out too late that `*.md` and `*.json` are generated from *.xml. Hence my comments are on the `*.json` file.

2023-06-27 13:18 UTC, agoerler commented on vocabularies/Hierarchy.json
> +      "@Core.LongDescription": "The properties in this complex type contain information about\nan occurrence of a node in the result set of a hierarchical request.\nThey are derived when hierarchical
missing closing parenthesis: `filter(contains(Name, 'New York')` -> `filter(contains(Name, 'New York'))`

2023-06-27 14:35 UTC, HeikoTheissen commented on vocabularies/Hierarchy.json
> +        "@Core.Description": "Type of a node",
`Edm.String` is the default value for `$Type` in CSDL JSON, thus can be omitted.

2023-06-27 14:55 UTC, agoerler approved these changes

2023-07-06 06:39 UTC, HeikoTheissen commented
Shall we include an (SAP-specific) annotation for cycles here? Because the OASIS vocabulary does not contain one.

2023-07-06 12:04 UTC, ThomasChadzelek commented
> Shall we include an (SAP-specific) annotation for cycles here? Because the OASIS vocabulary does not contain one.

Cycles? I was always under the impression that a tree is a special case of a directed **acyclic** graph ;-)

2023-07-07 15:01 UTC, uhlmannm commented
> > Cycles? I was always under the impression that a tree is a special case of a directed **acyclic** graph ;-)
> 
> Not at SAP. ![image](https://user-images.githubusercontent.com/67904016/251459002-47ffabce-dba8-4d84-b688-6ee4ddeb9229.png)

Would it make sense to discuss this case when it comes up? For me it is unclear what such a hierarchy would mean. The node for "Anne" is in the tree twice (somewhat like a multiple parents case) but its children have to be included only in one of the places.

2023-09-05 14:36 UTC, merged