Added Source Event for Side Effects
SAP/odata-vocabularies pull request #284
Opened 2023-09-14 14:47 UTC by martin4all

2023-09-14 16:20 UTC, RaizoC commented
Not sure we should add a constraint, that either source properties and entities XOR source events can be defined on source side.

2023-09-14 16:22 UTC, RaizoC commented
Is it really an "event" that triggers the side effect from UI side or a "notification" (-> amc://notification/notify)?

2023-09-15 07:25 UTC, martin4all commented
> Is it really an "event" that triggers the side effect from UI side or a "notification" (-> amc://notification/notify)?

We use the term "event" in backed (BDEF). Therefore it's named _SourceEvents_. To make it consistent we can also rename the AMC to amc://event/raise. But I'm also fine if we use notification ...

2023-09-27 06:33 UTC, MarcelWaechter commented
Hi,
may I ask if we really need this separation of having events that triggers a side effect which then contains the target(s) to be refreshed... or if this is not like a server driven event that already contains the targets to be refreshed (not the data but the targets so we send GET requests same as we would do for side effects)
In this case the server could be even more precise as it knows what fields were changed so the client need to request them only.
Otherwise apps annotate a side effect with 5 targets that might be affected. Once the event is triggered the client then need to refresh all 5 properties.

2023-09-27 07:27 UTC, martin4all commented
> Hi, may I ask if we really need this separation of having events that triggers a side effect which then contains the target(s) to be refreshed... or if this is not like a server driven event that already contains the targets to be refreshed (not the data but the targets so we send GET requests same as we would do for side effects) In this case the server could be even more precise as it knows what fields were changed so the client need to request them only. Otherwise apps annotate a side effect with 5 targets that might be affected. Once the event is triggered the client then need to refresh all 5 properties.

2023-09-27 07:32 UTC, HeikoTheissen commented
Since you closed this, does it mean that we don't need the `WebSocketChannel` annotation anymore?

2023-09-27 07:32 UTC, martin4all commented
> > Hi, may I ask if we really need this separation of having events that triggers a side effect which then contains the target(s) to be refreshed... or if this is not like a server driven event that already contains the targets to be refreshed (not the data but the targets so we send GET requests same as we would do for side effects) In this case the server could be even more precise as it knows what fields were changed so the client need to request them only. Otherwise apps annotate a side effect with 5 targets that might be affected. Once the event is triggered the client then need to refresh all 5 properties.

2023-09-27 07:34 UTC, martin4all commented
There are 2 issues to my understanding:
1. Here we have the same issue as we have it for the key properties: The server does not speak OData which means it does not know entity sets, entity types, or navigation properties. This is only known when creating the $metadata of the service.
2. The servicer does not really know which data has been changed. We have to rely on the correct implementation of the business object that the event is raised correctly. (But for non-event driven side effects we already have possibility that a change of one fields can affect several other fields.)

2023-09-27 07:36 UTC, martin4all commented
> Since you closed this, does it mean that we don't need the `WebSocketChannel` annotation anymore?
Sorry, closed by accident ...

2023-12-15 08:53 UTC, HeikoTheissen approved these changes

2023-12-15 08:56 UTC, MarcelWaechter approved these changes
the initial description of the PR isn't up-to-date anymore, still contains the key binding etc. you might also want to update this?
But anyhow, looks good to me, but for sure good if Martin/Renzo also have a look

Thanks

2023-12-15 09:02 UTC, ralfhandl commented
How about "rescuing" the still relevant parts of the PR description into a Markdown file in the `examples` folder similar to the document [Annotating capabilities](https://github.com/oasis-tcs/odata-vocabularies/blob/main/examples/Org.OData.Capabilities.V1.capabilities.md)?

Side effects aren't the most straight-forward topic and deserve a little more documentation than the pure term description.

2023-12-15 09:05 UTC, ralfhandl requested changes
Please add more documentation

2023-12-21 08:46 UTC, MarcelWaechter commented
Hi,
our UX came up with the idea to have different interaction types:
- notification: the User is just notified, the data is refreshed immediately (our default)
- confirmation: the User will be asked if data shall be refreshed or not
- none: the data is refreshed without any kind of interaction

My initial idea was that this shall be an app configuration (manifest setting), but I was asked if this can't be also part of the annotation.
What is your thought on this?

2023-12-21 09:22 UTC, HeikoTheissen commented
If different SourceEvents can have different interaction types, I would put this into the annotation.

2023-12-21 09:25 UTC, MarcelWaechter commented
yes, every event event could have a different interaction type

2023-12-21 09:29 UTC, RaizoC commented
> yes, every event event could have a different interaction type

having it as annotation might be ok, but not sure it would be correct in the side effects annotation as how the UI reacts on one and the same side effect depends on the UI, so maybe this has to be added rather to the UI-annotations domain (especially as I doubt that the setting is specific for different side effects, but a global setting for the UI overall)

2023-12-22 08:31 UTC, MarcelWaechter commented
> > yes, every event event could have a different interaction type
> 
> having it as annotation might be ok, but not sure it would be correct in the side effects annotation as how the UI reacts on one and the same side effect depends on the UI, so maybe this has to be added rather to the UI-annotations domain (especially as I doubt that the setting is specific for different side effects, but a global setting for the UI overall)

Yes, I agree they would not make so much sense in the Common but only in the UI vocabulary, and then I'm not sure on how we could have an understandable annotation with a connection to the side effects events. 
I personally think apps will anyway use only the default (notification).
 
I'd therefore start with a manifest setting, we could still provide it later if really needed

2024-11-28 15:57 UTC, ralfhandl commented on vocabularies/Common.xml
> +          &lt;dt&gt;`draft` &lt;dd&gt;collaborative draft; the parameter value is explained in the documentation
Which documentation is meant here? Please add links to the documentation.

2024-12-10 08:36 UTC, ralfhandl requested changes
+1, please add link to ABAP Push Channel Protocol

2024-12-10 08:36 UTC, ralfhandl commented on vocabularies/Common.xml
> +          <String>Messages sent over the channel follow the ABAP Push Channel protocol.
```suggestion
          <String>Messages sent over the channel follow the [ABAP Push Channel protocol](https://community.sap.com/t5/application-development-blog-posts/specification-of-the-push-channel-protocol-pcp/ba-p/13137541).
```

2024-12-10 08:45 UTC, HeikoTheissen approved these changes

2024-12-10 08:46 UTC, ralfhandl approved these changes

2024-12-10 08:47 UTC, merged