Adding ODM annotation @ODM.oidReference.entityName
SAP/odata-vocabularies pull request #289
Opened 2023-10-23 22:08 UTC by ArkadiyPonomarov

Added

- ODM annotation @ODM.oidReference.entityName (same name in CDS)

2023-10-23 22:12 UTC, ArkadiyPonomarov commented
@ralfhandl Could you please review?

2023-10-24 14:47 UTC, ralfhandl requested changes
Looks good, just add "Experimental" on both term and property until it has been implemented by SAP NetWeaver AS ABAP

2023-10-24 14:58 UTC, ArkadiyPonomarov commented
Changes are done, thank you.

2023-10-24 15:01 UTC, ralfhandl approved these changes

2023-10-24 15:24 UTC, HeikoTheissen requested changes

2023-10-24 15:24 UTC, HeikoTheissen commented on vocabularies/ODM.xml
> +        <Annotation Term="Core.Description" String="Specification of an referenced entity" />
```suggestion
        <Annotation Term="Core.Description" String="Specification of a referenced entity" />
```

2023-10-24 16:15 UTC, HeikoTheissen submitted a review, later dismissed

2023-10-25 07:28 UTC, ralfhandl approved these changes

2023-11-04 19:50 UTC, ArkadiyPonomarov commented
Hi colleagues, Is there any stopper? If not, could you please review/approve?

2023-11-06 13:45 UTC, martin4all approved these changes

2023-11-06 13:47 UTC, merged