Mapping Semantic Object property -> constant
SAP/odata-vocabularies pull request #334
Opened 2024-07-23 12:26 UTC by HeikoTheissen

2024-07-23 14:37 UTC, ralfhandl requested changes

2024-07-23 14:37 UTC, ralfhandl commented on vocabularies/Common.xml
> +        <Property Name="LocalProperty" Type="Edm.PrimitiveType" Nullable="false">
```suggestion
        <Property Name="Constant" Type="Edm.PrimitiveType" Nullable="false">
```

2024-07-23 14:47 UTC, ralfhandl approved these changes

2024-07-24 07:13 UTC, martin4all approved these changes

2024-09-19 06:26 UTC, merged