Feat/dpp extension
SAP/odata-vocabularies pull request #352
Opened 2024-10-22 14:57 UTC by sthesse

Updating 3 descriptions based on experts reviews.

2024-10-22 15:26 UTC, HeikoTheissen requested changes

2024-10-22 15:26 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +                <String>The unique identifier for the purpose of processing of personal data. Any processing of personal data is based on a specified, explicit, and legitimate purposes and not furthe
"based on a ... purposes" - delete the "a"

2024-10-22 15:26 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +          <String>Property contains potentially sensitive personal data. Sensitive personal data is a category of personal data that needs special handling. The determination which personal data that
"which personal data is sensitive" (omit the "that")

2024-10-23 14:19 UTC, ralfhandl submitted a review, later dismissed

2024-10-24 07:28 UTC, HeikoTheissen requested changes

2024-10-24 07:28 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
>                <Annotation Term="Core.Description" String="The unique identifier for the purpose of a consent" />
```suggestion
              <Annotation Term="Core.Description" String="The unique identifier for the purpose of a processing of personal data" />
```
The Description speaks of the "purpose of a consent", but the LongDescription speaks of the "purpose of data processing". This is confusing.

2024-10-24 07:28 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +                <String>The unique identifier for the purpose of processing of personal data. Any processing of personal data is based on specified, explicit, and legitimate purposes and not further
```suggestion
                <String>Any processing of personal data is based on specified, explicit, and legitimate purposes, and data are not further processed in a manner that is incompatible with those purposes. The purposes are defined by the data controller or joint data controllers.
```
- Do not repeat the Description in the LongDescription.
- I split the sentence in two (separated by a new comma), the previous wording was unclear to me.
- Clarify the role of the consent. I assume that any given purpose must be based on either a legitimate interest of on the consent of the data owner.

2024-10-24 07:28 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +          <String>Property contains potentially personal data. Personal data describes any information which is related to an identified or identifiable natural person (data subject). An identifiable
```suggestion
          <String>Personal data describes any information which is related to an identified or identifiable natural person (data subject). An identifiable person is one who can be identified, directly or indirectly, in particular by a reference to an identifier such as a name, an identification number, location data, an online identifier, or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural, or social identity of that natural person. Note: properties annotated with [`FieldSemantics`](#FieldSemantics) need not be additionally annotated with this term.
```

2024-10-24 07:28 UTC, HeikoTheissen commented on vocabularies/PersonalData.xml
> +          <String>Property contains potentially sensitive personal data. Sensitive personal data is a category of personal data that needs special handling. The determination which personal data is s
```suggestion
          <String>Sensitive personal data is a category of personal data that needs special handling. The determination which personal data is sensitive may differ for different legal areas or industries. Examples of sensitive personal data:
```

2024-10-24 10:50 UTC, HeikoTheissen approved these changes

2024-10-24 11:53 UTC, ralfhandl approved these changes

2024-10-28 14:52 UTC, merged