New term Common.ActionSemantics
SAP/odata-vocabularies pull request #83
Opened 2021-01-25 15:28 UTC by ralfhandl

2021-01-26 12:30 UTC, BerSie submitted a review, later dismissed

2021-01-26 12:41 UTC, RaizoC commented
Hmm, now reading it the copy-semantics seems very special and is taken out of the create semantics. I do not understand how this different and more special semantics impacts anything on client side different than the pure "create"-semantics (which I think is very valid). If there really is a use case to handle that one differently (does it need to be unique?) further constraints need to be added to the "copy" semantics, i.e. that it is a bound "create"-action that has the same (bound) entity as result entity.

2021-01-26 12:52 UTC, ralfhandl commented
@RaizoC currently we only have a use case for "copy". Should I remove "create" for now, or comment it out?

2021-01-26 12:54 UTC, BerSie commented
> Hmm, now reading it the copy-semantics seems very special and is taken out of the create semantics. I do not understand how this different and more special semantics impacts anything on client side different than the pure "create"-semantics (which I think is very valid). If there really is a use case to handle that one differently (does it need to be unique?) further constraints need to be added to the "copy" semantics, i.e. that it is a bound "create"-action that has the same (bound) entity as result entity.

I think the UI can check if an entry was selected before activating the copy function (it knows that an instance has to be selected). For create (simple create without reference) you would not expect that.

2021-01-26 12:56 UTC, RaizoC commented
My feedback rather goes into the direction that this is too specific as the client might only be interested in the "create"-semantics. The UI selection depends on whether the action is instance-bound or not, so for this no semantics is needed. What else would the client do with this information?

2022-01-19 08:53 UTC, RaizoC commented
I still wonder if these semantics are disjoint, i.e. from the description every "copy" action would also be tagged as "create" action. Is this the intention or does "copy" implies the "create" fact?

2022-01-19 09:17 UTC, ralfhandl commented
We can remove "create" for now because https://jira.tools.sap/browse/FIORITECHP1-20377 only requires "copy"

2022-06-22 07:47 UTC, ArunBharathiKumarasamy submitted a review, later dismissed

2022-06-22 07:53 UTC, RaizoC approved these changes

2022-09-07 13:56 UTC, BerSie commented
Why did we put it on the DataFieldForAction and not on the action itself (it should be bound to the action and not its usage/reference)? Sometimes these pull requests are running too long :-) (at least for my old brain).

2022-09-07 14:03 UTC, ralfhandl commented
> Why did we put it on the DataFieldForAction and not on the action itself (it should be bound to the action and not its usage/reference)?

Good point!

2022-09-07 15:54 UTC, RaizoC submitted a review, later dismissed

2022-09-26 07:48 UTC, RaizoC approved these changes
FE already implemented the same.

2022-09-26 07:53 UTC, merged

2022-09-26 07:54 UTC, ralfhandl commented
> FE already implemented the same.

I've kept it "experimental", please notify me once this has also been implemented in RAP and proven to work end-to-end.

Thanks in advance!

2022-09-26 07:55 UTC, HeikoTheissen requested changes
Add links

2022-09-26 07:55 UTC, HeikoTheissen commented on vocabularies/UI.xml
> +        <Annotation Term="Core.Description" String="The annotated `DataFieldForAction` record within a `UI.LineItem` annotation references an action that deep-copies an instance of the annotated enti
```suggestion
        <Annotation Term="Core.Description" String="The annotated [`DataFieldForAction`](#DataFieldForAction) record within a [`UI.LineItem`](#LineItem) annotation references an action that deep-copies an instance of the annotated entity type" />
```

2022-09-26 07:55 UTC, HeikoTheissen commented on vocabularies/UI.xml
> +          <String>The referenced action MUST be bound to the annotated entity type and creates a new instance of the same entity type as a deep copy of the bound instance.
```suggestion
          <String>The referenced action MUST be bound to the annotated entity type and create a new instance of the same entity type as a deep copy of the bound instance.
```